version: "3"

services:
  broker-mqtt:
    image: eclipse-mosquitto
    ports:
      - "9001:9001"
      - "1883:1883"
    volumes:
      - TPI_broker_mqtt_data:/mosquitto/data            
  store-mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment: 
        - storageEngine=wiredTiger
    volumes: 
      - TPI_store_mongo_db:/data/db
  keycloak-mysql:
     image: mysql:5.6
     ports:
       - "3306:3306"
     environment:
         - MYSQL_ROOT_PASSWORD=keycloak
         - MYSQL_DATABASE=keycloak
         - MYSQL_USER=keycloak
         - MYSQL_PASSWORD=keycloak
     volumes:
       - TPI_keycloak_mysql_data:/var/lib/mysql
  keycloak:
       image: nebulaetpi/keycloak:latest
       environment:
         - MYSQL_ADDR=keycloak-mysql
         - MYSQL_PORT_3306_TCP_ADDR=keycloak-mysql
         - MYSQL_PORT_3306_TCP_PORT=3306
         - KEYCLOAK_USER=keycloak
         - KEYCLOAK_PASSWORD=keycloak
         - MYSQL_DATABASE=keycloak
         - MYSQL_USER=keycloak
         - MYSQL_PASSWORD=keycloak
         - SERVICE_PORTS=8080
       ports:
         - 8443:8443
         - 8080:8080
         - 9990:9990
       volumes:
         - TPI_keycloak_data:/opt/jboss/keycloak/standalone/data      
       depends_on: 
         - keycloak-mysql
volumes: 
  TPI_store_mongo_db:
  TPI_broker_mqtt_data:
  TPI_keycloak_mysql_data:
  TPI_keycloak_data: